name: maseef_app
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_switch: ^0.3.2
  flutter_svg_provider: ^1.0.3
  intl: ^0.17.0
  equatable: ^2.0.5
  image_picker: ^1.0.6
  google_maps_flutter: ^2.5.1
  location: ^5.0.3
  flutter_expanded_tile: ^0.3.7
  flutter_datetime_picker_plus: ^2.1.0
  geocoding: ^2.1.1
  lottie: ^2.7.0
  toggle_switch: ^2.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/json/
  fonts:
    - family: Gilroy
      fonts: 
        - asset: assets/fonts/GilroySemiBold.ttf
          weight: 600
        - asset: assets/fonts/GilroyMedium.ttf
          weight: 500
        - asset: assets/fonts/GilroyRegular.ttf
          weight: 400
        - asset: assets/fonts/GilroyBold.ttf
          weight: 700
        - asset: assets/fonts/GilroyRegularItalic.ttf
          weight: 400
    - family: SF Pro Text
      fonts: 
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProTextBold.ttf
          weight: 700
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanSemiBold.ttf
          weight: 600
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Sarala
      fonts: 
        - asset: assets/fonts/SaralaBold.ttf
          weight: 700
    - family: Helvetica Neue
      fonts: 
        - asset: assets/fonts/HelveticaNeue.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Open Sans
      fonts: 
        - asset: assets/fonts/OpenSansRomanRegular.ttf
          weight: 400
    - family: Lato
      fonts: 
        - asset: assets/fonts/LatoBold.ttf
          weight: 700
    - family: Amal
      fonts:
        - asset: assets/fonts/Amal_SemiBold.otf
          weight: 500
        - asset: assets/fonts/Amal_Bold.otf
          weight: 600
        - asset: assets/fonts/Amal.otf
          weight: 400
